# Book settings
title: Website Statis KAL
author: Abdul Hadi Marzuqi
copyright: "2026"
logo: abdul_hadi_marzuqi.jpeg # Berkas foto logo kustom Abdul Hadi Marzuqi

# Execution settings
execute:
  execute_notebooks: auto

# HTML settings
html:
  use_issues_button: false
  use_repository_button: false
  comments:
    hypothesis: false
    utterances: false

# Build settings
exclude_patterns:
  - materi/index.md
  - tugas/index.md

